module.exports = {
	randomEncounterCards: [{
		name: "Caller",
		text: "Hey mister DJ...my friends and I are throwing it back at the disco tonight. Play us something to get us there?",
		successText: "Aw yeah, we're feeling that. Thanks sugar :)",
		failureText: "Hmmmm...maybe next time, honey.",
		resistance: "funky",
		image: "/img/caller1.jpeg",
		successImage: "/img/caller1_success.jpeg",
		failureImage: "/img/caller1_fail.jpeg",
		entranceSoundID: "callerEntrance",
		successSoundID: "callerSuccess",
		failureSoundID: "callerFailure",
	}, {
		name: "Producer",
		text: "Kid! I don't get it...we're just not clicking with the young kids of today. Do something about it!",
		successText: "Ratings are through the roof! Good work kid.",
		failureText: "Ah, crap...guess I'm gonna have to hold off on that boat for a little bit longer...",
		resistance: "pump",
		image: "/img/producer1.jpeg",
		successImage: "/img/producer1_success.jpeg",
		failureImage: "/img/producer1_fail.jpeg",
		entranceSoundID: "producerEntrance",
		successSoundID: "producerSuccess",
		failureSoundID: "producerFailure",
	}, {
		name: "Evening",
		text: "You look out over the twinkling lights of LA. The air is cool, quiet, pensive. What do all of those night souls want to hear tonight?",
		successText: "Yeah. That was the right track. You can feel it.",
		failureText: "Huh. That didn't feel right. Gotta switch it up a little bit.",
		resistance: "chillout",
		image: "/img/evening1.jpeg",
		successImage: "/img/evening1_success.jpeg",
		failureImage: "/img/evening1_fail.jpeg",
		entranceSoundID: "eveningEntrance",
		successSoundID: "eveningSuccess",
		failureSoundID: "eveningFailure",
	}],
	scriptedEncounterCards: []
}
